version: "3.9"

services:
  mysql:
    image: mysql:8.4

    container_name: activos-fijos-mysql

    restart: unless-stopped

    ports:
      - "3307:3306"

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: activos_fijos
      MYSQL_USER: activos
      MYSQL_PASSWORD: activos123

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot" ]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  mysql_data:
